/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-14 01:39:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.home;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.trabajouy.model.EstadoSesion;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/inicioSesion.css", Long.valueOf(1699925636000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"es\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Mi Página Web</title>\n");
      out.write(" \n");
      out.write("    <style>\n");
      out.write("        ");
      out.write("*, *::before, *::after {\n");
      out.write("    box-sizing: border-box;\n");
      out.write("}\n");
      out.write("\n");
      out.write("body {\n");
      out.write("    font-family: 'Montserrat', sans-serif;\n");
      out.write("    background-color: #28666e;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    display: flex;\n");
      out.write("    justify-content: center;\n");
      out.write("    align-items: center;\n");
      out.write("    height: 100vh;\n");
      out.write("    overflow-x: hidden;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container, .login-form input, .login-form button {\n");
      out.write("    max-width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".container {\n");
      out.write("    background-color: rgba(255, 255, 255, 0.9);\n");
      out.write("    padding: 2em 3em;\n");
      out.write("    border-radius: 10px;\n");
      out.write("    box-shadow: 10px 10px 15px rgba(0, 0, 0, 0.2);\n");
      out.write("    width: 350px;\n");
      out.write("    margin-top: 10px;\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    border-radius: 25px;\n");
      out.write("    text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".logo {\n");
      out.write("    width: 150px;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form h2 {\n");
      out.write("    color: #333;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("    font-weight: 400;\n");
      out.write("    border-bottom: 2px solid #0099ff;\n");
      out.write("    display: inline-block;\n");
      out.write("    padding-bottom: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form input {\n");
      out.write("    width: 100%;\n");
      out.write("    padding: 12px;\n");
      out.write("    margin: 8px 0;\n");
      out.write("    border: 2px solid #ddd;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    font-size: 16px;\n");
      out.write("    outline: none;\n");
      out.write("    transition: border-color 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form input:focus {\n");
      out.write("    border-color: #28666e;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form button {\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    border: none;\n");
      out.write("    background-color: #28666e;\n");
      out.write("    color: #fff;\n");
      out.write("    border-radius: 20px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    font-size: 19px;\n");
      out.write("    transition: background-color 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-form button:hover {\n");
      out.write("    background-color: #0077cc;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 768px) {\n");
      out.write("    .container {\n");
      out.write("        width: 90%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .login-form h2 {\n");
      out.write("        font-size: 18px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .login-form input, .login-form button {\n");
      out.write("        font-size: 14px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .logo {\n");
      out.write("        width: 100px;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media (max-width: 480px) {\n");
      out.write("    .container {\n");
      out.write("        padding: 1em 1.5em;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300&display=swap\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <img src=\"media/images/logo2.png\" alt=\"Logo\" class=\"logo\">\n");
      out.write("        <div class=\"login-form\">\n");
      out.write("            <h2>Iniciar Sesión</h2>\n");
      out.write("            ");
 EstadoSesion sesion = (EstadoSesion) request.getSession().getAttribute("estado_sesion"); 
            if (sesion == EstadoSesion.BAD_LOGIN) { 
                String mensajeError = (String) request.getSession().getAttribute("error_sesion");
            
      out.write("\n");
      out.write("            <p style = \"color: red;\">");
      out.print( mensajeError );
      out.write("</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <form method=\"post\">\n");
      out.write("                <input type=\"text\" name=\"nickname\" placeholder=\"Usuario\" required>\n");
      out.write("                <input type=\"password\" name=\"contrasena\" placeholder=\"Contraseña\" required>\n");
      out.write("                <button type=\"submit\">Entrar</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
