/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2023-11-09 04:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import net.java.dev.jaxb.array.StringArray;
import com.trabajouy.model.EstadoSesion;
import java.util.List;

public final class leftPanel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/left-panel.css", Long.valueOf(1699477528000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.java.dev.jaxb.array.StringArray");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <style>\r\n");
      out.write("            ");
      out.write("* {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel {\r\n");
      out.write("  width: 250px;\r\n");
      out.write("  background-color: #f7f9fa;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  max-height: 1200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel h2 {\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  color: #28666e;\r\n");
      out.write("  border-bottom: 2px solid #28666e;\r\n");
      out.write("  padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel li {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  background-color: #28666e;\r\n");
      out.write("  color: #f4f4f4;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel ul {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel li:hover {\r\n");
      out.write("  transform: translateY(-5px);\r\n");
      out.write("  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("\r\n");
      out.write("  .left-panel {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section div {\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".keywords-panel {\r\n");
      out.write("  flex-basis: 20%;\r\n");
      out.write("  min-width: 200px;\r\n");
      out.write("  flex-grow: 0; \r\n");
      out.write("  flex-shrink: 0; \r\n");
      out.write("  margin-right: 2em; \r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: transparent; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-panel {\r\n");
      out.write("  flex-basis: 20%;\r\n");
      out.write("  min-width: 200px;\r\n");
      out.write("  flex-grow: 0; \r\n");
      out.write("  flex-shrink: 0; \r\n");
      out.write("  margin-right: 2em; \r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: transparent; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile-panel h2 {\r\n");
      out.write("  font-size: 24px;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  color: #28666e;\r\n");
      out.write("  border-bottom: 2px solid #28666e;\r\n");
      out.write("  padding-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel a:hover {\r\n");
      out.write("  text-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".left-panel a {\r\n");
      out.write("  color: inherit; \r\n");
      out.write("  text-decoration: none; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".keywords-section-visitante {\r\n");
      out.write("  flex-basis: 20%;\r\n");
      out.write("  min-width: 200px;\r\n");
      out.write("  flex-grow: 0; \r\n");
      out.write("  flex-shrink: 0; \r\n");
      out.write("  margin-right: 2em; \r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: transparent; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </style>\r\n");
      out.write("       		 	<div class=\"left-panel\">\r\n");
      out.write("        			 <div class=\"profile-panel\">\r\n");
      out.write("                         ");

                         	if (request.getSession().getAttribute("estado_sesion") == EstadoSesion.EMPRESA) {
                         
      out.write("\r\n");
      out.write("                         <a href=\"perfil\">\r\n");
      out.write("                            <h2>Mi Perfil</h2>\r\n");
      out.write("                         </a>\r\n");
      out.write("                         <ul>\r\n");
      out.write("                            <a href=\"oferta\"><li>Alta Oferta Laboral</li></a>\r\n");
      out.write("		                    <a href=\"compra-paquete\"><li>Comprar Paquetes</li></a>\r\n");
      out.write("		                    <a href=\"consulta-paquete\"><li>Consultar Paquetes</li></a>\r\n");
      out.write("		                    <a href=\"consultaOferta\"><li>Consultar Ofertas</li></a>\r\n");
      out.write("		                    <a href=\"perfil\"><li>Consultar Postulaciones</li></a>\r\n");
      out.write("		                    <a href=\"tipo-oferta\"><li>Consultar Tipos Publicación</li></a>\r\n");
      out.write("		                    <a href=\"usuarios\"><li>Consultar Usuarios</li></a>\r\n");
      out.write("		                    <a href=\"seleccionar-postulacion\"><li>Seleccionar Postulación</li></a>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        ");

	                       	} else {
	                       		if (request.getSession().getAttribute("estado_sesion") == EstadoSesion.POSTULANTE) {
                        
      out.write("\r\n");
      out.write("	                        <a href=\"perfil\">\r\n");
      out.write("	                            <h2>Mi Perfil</h2>\r\n");
      out.write("	                        </a>\r\n");
      out.write("	                        <ul>\r\n");
      out.write("	                            <a href=\"ofertas-postularse\"><li>Postularse a Oferta</li></a>\r\n");
      out.write("			                    <a href=\"consultaOferta\"><li>Consultar Ofertas</li></a>\r\n");
      out.write("			                    <a href=\"consulta-paquete\"><li>Consultar Paquetes</li></a>\r\n");
      out.write("			                    <a href=\"perfil\"><li>Consultar Postulaciones</li></a>\r\n");
      out.write("			                    <a href=\"tipo-oferta\"><li>Consultar Tipos Publicación</li></a>\r\n");
      out.write("			                    <a href=\"usuarios\"><li>Consultar Usuarios</li></a>\r\n");
      out.write("	                        </ul>\r\n");
      out.write("	                     ");

	                       		} else {
	                     
      out.write("\r\n");
      out.write("		                     <a href=\"home\">\r\n");
      out.write("	                            <h2>Inicio</h2>\r\n");
      out.write("	                         </a>\r\n");
      out.write("	                     	<ul>\r\n");
      out.write("	                            <a href=\"consultaOferta\"><li>Consultar Ofertas</li></a>\r\n");
      out.write("			                    <a href=\"consulta-paquete\"><li>Consultar Paquetes</li></a>\r\n");
      out.write("			                    <a href=\"tipo-oferta\"><li>Consultar Tipos Publicación</li></a>\r\n");
      out.write("			                    <a href=\"usuarios\"><li>Consultar Usuarios</li></a>\r\n");
      out.write("	                        </ul>\r\n");
      out.write("	                     ");

	                       		}
	                       	}
	                     
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"keywords-section\">\r\n");
      out.write("                        <h2>Keywords</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                        ");

                        	if (request.getSession().getAttribute("keywords_leftpanel") != null) {
                        		
                        		List<String> info = (List<String>)  request.getSession().getAttribute("keywords_leftpanel");
                        	
                        		for (String keyword : info ) 
                        			
                        		{
                        
      out.write("\r\n");
      out.write("                        <a href=\"consultaOferta?opcionK=");
      out.print(keyword);
      out.write("\"><li>");
      out.print(keyword );
      out.write("</li></a>\r\n");
      out.write("                         ");

                        	}
                        }
                        
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
