/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2023-11-09 04:12:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.usuarios;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import servidor.DtPostulacionArray;
import java.util.List;
import servidor.DtCompraPaqueteArray;
import java.io.ObjectInputStream.GetField;
import com.trabajouy.model.EstadoSesion;
import java.util.Date;
import java.util.Vector;
import java.util.Map;
import servidor.DtUsuario;
import servidor.DtEmpresa;
import servidor.DtPostulante;
import servidor.DtPublicar;
import servidor.DtPostulacion;
import servidor.DtCompraPaquete;

public final class perfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/consultarPerfil.css", Long.valueOf(1699477528000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("servidor.DtEmpresa");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("servidor.DtPostulante");
    _jspx_imports_classes.add("servidor.DtCompraPaqueteArray");
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("servidor.DtCompraPaquete");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("servidor.DtPublicar");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("servidor.DtPostulacion");
    _jspx_imports_classes.add("servidor.DtPostulacionArray");
    _jspx_imports_classes.add("servidor.DtUsuario");
    _jspx_imports_classes.add("java.io.ObjectInputStream.GetField");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Perfil</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        ");
      out.write("a:link, a:visited, a:active, a:hover {\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main, .general-info, .menu-bar {\r\n");
      out.write("    display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main{\r\n");
      out.write("   justify-content: baseline;\r\n");
      out.write("   padding: 1.5em;\r\n");
      out.write("   gap: 6em;\r\n");
      out.write("   background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write(".menu-bar button {\r\n");
      out.write("    padding: 10px 15px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    letter-spacing: 0.5px;\r\n");
      out.write("    background-color: #28666e;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-container li:hover {\r\n");
      out.write("    transition: 100ms;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-panel img, .general-info img {\r\n");
      out.write("    border: 3px solid #28666e;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    height: 150px;\r\n");
      out.write("    margin: 1em;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write(".center-panel img:hover {\r\n");
      out.write("    transform: translateY(-5px);\r\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".info-container {\r\n");
      out.write("    width: 800px;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("    font-size: large;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".general-info .name-and-more {\r\n");
      out.write("    margin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar .derecha {\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding-right: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".info-container ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".name-and-more h1, .name-and-more h2, .name-and-more h3, .center-panel .name-and-more h1, .center-panel .name-and-more h2, .center-panel .name-and-more h3 {\r\n");
      out.write("    margin: 5px 0;\r\n");
      out.write("    color: #28666e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar button:hover {\r\n");
      out.write("    background-color: #1c4c56;\r\n");
      out.write("    transform: translateY(-3px);\r\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".detailed-info {\r\n");
      out.write("    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    background-color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar {\r\n");
      out.write("    justify-content: baseline;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button {\r\n");
      out.write("    padding: 10px 20px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    background-color: #f3f4f6;\r\n");
      out.write("    transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button:hover {\r\n");
      out.write("    background-color: #e1e2e5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button.active {\r\n");
      out.write("    background-color: #28666e;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-aligned {\r\n");
      out.write("    margin-left: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-container li p {\r\n");
      out.write("    margin: 5px 0;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-container li:last-child p {\r\n");
      out.write("    border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".list-item {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("    transition: transform 0.3s;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-info {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 20px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    flex: 3;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-info img {\r\n");
      out.write("    width: 100px;\r\n");
      out.write("    height: 100px;\r\n");
      out.write("    object-fit: cover;\r\n");
      out.write("    max-width: 150px;\r\n");
      out.write("    border-radius: 5px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-item:hover {\r\n");
      out.write("    box-shadow: 0 6px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("    border: 3px solid #28666e;\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  .list-block {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-block h2 {\r\n");
      out.write("    font-size: 1.5em;\r\n");
      out.write("    color: #28666e;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-block ul {\r\n");
      out.write("    padding-left: 20px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .list-buy {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    flex: 1;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/header.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"main\">\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/leftPanel.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"center-panel\">\r\n");
      out.write("            <div class=\"general-info\">\r\n");
      out.write("                <img id=\"profile-photo\" src=\"/trabajouy/media/images/");
      out.print( (String)((DtUsuario) request.getSession().getAttribute("info_perfil")).getFoto() );
      out.write("\"/>\r\n");
      out.write("                <div class=\"name-and-more\">\r\n");
      out.write("                    <h1>");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getNombre() +" "+ ((DtUsuario) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</h1>\r\n");
      out.write("                    <h2>");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</h2>\r\n");
      out.write("                    <h3>Último Ingreso: <span id=\"last-date\">");
      out.print( new Date() );
      out.write("</span></h3>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"detailed-info\">\r\n");
      out.write("            ");

            	if (request.getSession().getAttribute("info_perfil") instanceof DtEmpresa) {
            
      out.write("\r\n");
      out.write("            	<div class=\"menu-bar\">\r\n");
      out.write("                    <button id=\"profile-button\">Perfil</button>\r\n");
      out.write("                    <button id=\"offers-button\" style=\"visibility:hidden;\">Ofertas Laborales</button>\r\n");
      out.write("                    <button id=\"packages-button\" style=\"visibility:hidden;\">Paquetes</button>\r\n");
      out.write("                    <a href=\"modificarUsuario\" style=\"visibility:hidden;\" id=\"edit-button\"><button class=\"menu-button right-aligned\">Editar</button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("            ");

            	}else {
            		if (request.getSession().getAttribute("info_perfil") instanceof DtPostulante) {
            
      out.write("\r\n");
      out.write("                <div class=\"menu-bar\">\r\n");
      out.write("                    <button class=\"menu-button active\" id=\"profile-button\">Perfil</button>\r\n");
      out.write("                    <button class=\"menu-button\" id=\"postulations-button\" style=\"visibility:hidden;\">Postulaciones</button>\r\n");
      out.write("                    <a href=\"modificarUsuario\" style=\"visibility:hidden;\" id=\"edit-button\"><button class=\"menu-button right-aligned\">Editar</button></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            ");

            		}
            	}
            
      out.write("\r\n");
      out.write("                <div id=\"info-container\" class=\"info-container\">\r\n");
      out.write("                ");

                servidor.PublicadorService service = new servidor.PublicadorService();
    			servidor.Publicador portPublicador = service.getPublicadorPort();
            		if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))) {
            	
      out.write("\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( (String) request.getSession().getAttribute("consultar_perfil") );
      out.write("</span></p></li>\r\n");
      out.write("                        <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("                ");

            		}else {
            		    
            			if (portPublicador.esPostulante((String) request.getSession().getAttribute("consultar_perfil"))) {
            	
      out.write("\r\n");
      out.write("	            	<ul>\r\n");
      out.write("                        <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( (String) request.getSession().getAttribute("consultar_perfil") );
      out.write("</span></p></li>\r\n");
      out.write("                        <li><p><b>Nombre: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Apellido: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Email: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Fecha de Nacimiento: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getFechaB() );
      out.write("</p></li>\r\n");
      out.write("                        <li><p><b>Nacionalidad: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNacionalidad() );
      out.write("</p></li>\r\n");
      out.write("	                </ul>\r\n");
      out.write("	            ");

            			}
            		}
            	
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("	<script>\r\n");
      out.write("	    ");

               String consultarPerfil = (String) request.getSession().getAttribute("consultar_perfil");
	           String nickSesion = (String) request.getSession().getAttribute("nickname_sesion");
	    
	       
	     	if (nickSesion !=null && nickSesion.equals(consultarPerfil)) {
	     		if (request.getSession().getAttribute("info_perfil") instanceof DtPostulante) {
    	
      out.write("\r\n");
      out.write("		    const postulationsButton = document.getElementById(\"postulations-button\");\r\n");
      out.write("		    const infoContainer = document.getElementById(\"info-container\");\r\n");
      out.write("		    const profileButton = document.getElementById(\"profile-button\");\r\n");
      out.write("		    const editButton = document.getElementById(\"edit-button\");\r\n");
      out.write("		    \r\n");
      out.write("		    editButton.style.visibility = \"visible\";\r\n");
      out.write("		    postulationsButton.style.visibility = \"visible\";\r\n");
      out.write("		    \r\n");
      out.write("		    profileButton.addEventListener(\"click\", () => {\r\n");
      out.write("		    	editButton.disabled = false;\r\n");
      out.write("		    	editButton.style.visibility= \"visible\";\r\n");
      out.write("		    	infoContainer.innerHTML = `<ul>\r\n");
      out.write("                    <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( request.getSession().getAttribute("nickname_sesion") );
      out.write("</span></p></li>\r\n");
      out.write("                    <li><p><b>Nombre: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\r\n");
      out.write("                    <li><p><b>Apellido: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\r\n");
      out.write("                    <li><p><b>Email: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\r\n");
      out.write("                    <li><p><b>Fecha de Nacimiento: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getFechaB() );
      out.write("</p></li>\r\n");
      out.write("                </ul>`;\r\n");
      out.write("		    })\r\n");
      out.write("		\r\n");
      out.write("		    postulationsButton.addEventListener(\"click\", () => {\r\n");
      out.write("		    	editButton.style.visibility= \"hidden\";\r\n");
      out.write("		    	editButton.disabled = true;\r\n");
      out.write("		    	infoContainer.innerHTML = `\r\n");
      out.write("		        ");
 
		        DtPostulacionArray postuArray = (DtPostulacionArray) request.getSession().getAttribute("postulaciones_perfil");     
		    	List<DtPostulacion> info =	postuArray.getItem();
		        for (DtPostulacion postu : info) {
		       
		        		
      out.write("\r\n");
      out.write("		        	<ul>\r\n");
      out.write("                         <li>\r\n");
      out.write("                         <a href=\"info-oferta?oferta=");
      out.print( postu.getOferta() );
      out.write("\">\r\n");
      out.write("	                       		<div class=\"list-item\">\r\n");
      out.write("	                       			 <div class=\"list-info\">\r\n");
      out.write("	                       			 <img src=\"/trabajouy/media/images/");
      out.print( postu.getUrlfoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("	                           			<div class=\"list-block\">\r\n");
      out.write("	                               			<h2>");
      out.print( postu.getOferta());
      out.write("</h2>\r\n");
      out.write("	                               			<ul>\r\n");
      out.write("	                                   			<li><b>Fecha de Postulación: </b>");
      out.print(postu.getFechaString());
      out.write("</li>\r\n");
      out.write("	                               			</ul>\r\n");
      out.write("	                           			</div>\r\n");
      out.write("	                       			</div>\r\n");
      out.write("	                   			</div>\r\n");
      out.write("                   			</a>\r\n");
      out.write("                     	</li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("                ");

     				}
                
      out.write("\r\n");
      out.write("		    `;}) \r\n");
      out.write("	    ");

        	} else {
        		
        			
        		if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))) {
        
      out.write("\r\n");
      out.write("	        const offersButton = document.getElementById(\"offers-button\");\r\n");
      out.write("	        const infoContainer = document.getElementById(\"info-container\");\r\n");
      out.write("	        const profileButton = document.getElementById(\"profile-button\");\r\n");
      out.write("	        const packagesButton = document.getElementById(\"packages-button\");\r\n");
      out.write("	        const editButton = document.getElementById(\"edit-button\");\r\n");
      out.write("	\r\n");
      out.write("	        editButton.style.visibility = \"visible\";\r\n");
      out.write("	        offersButton.style.visibility = \"visible\";\r\n");
      out.write("	        packagesButton.style.visibility = \"visible\";\r\n");
      out.write("	\r\n");
      out.write("	        profileButton.addEventListener(\"click\", () => {\r\n");
      out.write("	        	editButton.style.visibility = \"visible\";\r\n");
      out.write("	        	infoContainer.innerHTML = `<ul>\r\n");
      out.write("								        		<li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( request.getSession().getAttribute("nickname_sesion") );
      out.write("</span></p></li>\r\n");
      out.write("							                    <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\r\n");
      out.write("							                    <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\r\n");
      out.write("							                    <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\r\n");
      out.write("							                    <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\r\n");
      out.write("							                    <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\r\n");
      out.write("	                                        </ul>`;\r\n");
      out.write("	        })\r\n");
      out.write("	\r\n");
      out.write("	        offersButton.addEventListener(\"click\", () => {\r\n");
      out.write("	            editButton.style.visibility = \"hidden\";\r\n");
      out.write("	            infoContainer.innerHTML = `\r\n");
      out.write("	            ");
 
		        	for (DtPublicar publi : (Vector<DtPublicar>)request.getSession().getAttribute("publicaciones_perfil")) {
		            
		        		
      out.write("\r\n");
      out.write("	            							<ul>\r\n");
      out.write("	                                            <li>\r\n");
      out.write("	                                            <a href=\"info-oferta?oferta=");
      out.print(publi.getOferta() );
      out.write("&estado=");
      out.print( publi.getEstado() );
      out.write("\">\r\n");
      out.write("	                                            		<div class=\"list-item\">\r\n");
      out.write("	                                                		<div class=\"list-info\">\r\n");
      out.write("	                                                		<img src=\"/trabajouy/media/images/");
      out.print( publi.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("	                                                    		<div class=\"list-block\">\r\n");
      out.write("	                                                        		<h2>");
      out.print( publi.getOferta());
      out.write("</h2>\r\n");
      out.write("	                                                        		<ul>\r\n");
      out.write("	                                                            		<li><b>Estado: </b>");
      out.print( publi.getEstado());
      out.write("</li>\r\n");
      out.write("	                                                        		</ul>\r\n");
      out.write("	                                                    		</div>\r\n");
      out.write("	                                                		</div>\r\n");
      out.write("	                                            		</div>\r\n");
      out.write("	                                            	</a>\r\n");
      out.write("	                                        	</li>\r\n");
      out.write("	                                        </ul>\r\n");
      out.write("	            ");

     				}
                
      out.write("                              \r\n");
      out.write("	            `;})\r\n");
      out.write("	\r\n");
      out.write("	        packagesButton.addEventListener(\"click\", () => {\r\n");
      out.write("	            editButton.style.visibility = \"hidden\";\r\n");
      out.write("	            infoContainer.innerHTML = `\r\n");
      out.write("	            ");
 
	            DtCompraPaqueteArray mapaP = (DtCompraPaqueteArray) request.getSession().getAttribute("paquetes_comprados_perfil");
	            List<DtCompraPaquete> info = mapaP.getItem();
		        	for (DtCompraPaquete paquete : info) {
		         
		        		
      out.write("\r\n");
      out.write("	            							<ul>\r\n");
      out.write("	                                            <li>\r\n");
      out.write("	                                            <a href=\"info-paquete?nombre=");
      out.print( paquete.getPaquete() );
      out.write("\">\r\n");
      out.write("	                                            		<div class=\"list-item\">\r\n");
      out.write("	                                                		<div class=\"list-info\">\r\n");
      out.write("	                                                		<img src=\"/trabajouy/media/images/");
      out.print(  paquete.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("	                                                    		<div class=\"list-block\">\r\n");
      out.write("	                                                        		<h2>");
      out.print( paquete.getPaquete());
      out.write("</h2>\r\n");
      out.write("	                                                        		<ul>\r\n");
      out.write("	                                                            		<li><b>Fecha de Compra: </b>");
      out.print( paquete.getFecha());
      out.write("</li>\r\n");
      out.write("	                                                            		<li><b>Fecha de Vencimiento: </b>");
      out.print( paquete.getVencimiento());
      out.write("</li>\r\n");
      out.write("	                                                        		</ul>\r\n");
      out.write("	                                                    		</div>\r\n");
      out.write("	                                                		</div>\r\n");
      out.write("	                                            		</div>\r\n");
      out.write("	                                            	</a>\r\n");
      out.write("	                                        	</li>\r\n");
      out.write("	                                        </ul>\r\n");
      out.write("	          ");

		        	}
	          
      out.write("                              \r\n");
      out.write("	          `;})\r\n");
      out.write("        ");

        			}
        		}
	     	} else if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))){
	     		 
      out.write("\r\n");
      out.write("		           const offersButton = document.getElementById(\"offers-button\");\r\n");
      out.write("			       const infoContainer = document.getElementById(\"info-container\");\r\n");
      out.write("			       const profileButton = document.getElementById(\"profile-button\");\r\n");
      out.write("			       offersButton.style.visibility = \"visible\";\r\n");
      out.write("			       profileButton.addEventListener(\"click\", () => {\r\n");
      out.write("			        	infoContainer.innerHTML = `<ul>\r\n");
      out.write("										        		<li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNickname() );
      out.write("</span></p></li>\r\n");
      out.write("									                    <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\r\n");
      out.write("									                    <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\r\n");
      out.write("									                    <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\r\n");
      out.write("									                    <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\r\n");
      out.write("									                    <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\r\n");
      out.write("			                                        </ul>`;\r\n");
      out.write("			        })\r\n");
      out.write("			       offersButton.addEventListener(\"click\", () => {\r\n");
      out.write("			            infoContainer.innerHTML = `\r\n");
      out.write("			            ");
 
				        	for (DtPublicar publi : (Vector<DtPublicar>)request.getSession().getAttribute("publicacionesConfirmadas_perfil")) {
				       
				        		
      out.write("\r\n");
      out.write("			            							<ul>\r\n");
      out.write("			                                            <li>\r\n");
      out.write("			                                            <a href=\"info-oferta?oferta=");
      out.print( publi.getOferta());
      out.write("&estado=");
      out.print( publi.getEstado() );
      out.write("\">\r\n");
      out.write("			                                            		<div class=\"list-item\">\r\n");
      out.write("			                                                		<div class=\"list-info\">\r\n");
      out.write("			                                                		<img src=\"/trabajouy/media/images/");
      out.print( publi.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("			                                                    		<div class=\"list-block\">\r\n");
      out.write("			                                                        		<h2>");
      out.print( publi.getOferta());
      out.write("</h2>\r\n");
      out.write("			                                                        		<ul>\r\n");
      out.write("			                                                            		<li><b>Estado: </b>");
      out.print( publi.getEstado());
      out.write("</li>\r\n");
      out.write("			                                                        		</ul>\r\n");
      out.write("			                                                    		</div>\r\n");
      out.write("			                                                		</div>\r\n");
      out.write("			                                            		</div>\r\n");
      out.write("			                                            	</a>\r\n");
      out.write("			                                        	</li>\r\n");
      out.write("			                                        </ul>\r\n");
      out.write("			            ");

		     				}
		                
      out.write("                              \r\n");
      out.write("			            `;})\r\n");
      out.write("			       \r\n");
      out.write("			       ");
 
	     	}
        
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
