/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2023-11-09 04:13:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.usuarios;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.trabajouy.model.EstadoSesion;
import servidor.DtUsuario;
import servidor.DtOferta;
import servidor.DtPostulacion;
import java.util.Set;

public final class postulacion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/infoOfertaFrontend.css", Long.valueOf(1699494766000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("servidor.DtPostulacion");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("servidor.DtUsuario");
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
    _jspx_imports_classes.add("servidor.DtOferta");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Postulacion</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        ");
      out.write(".main-content {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: left;\r\n");
      out.write("  align-items: flex-start;\r\n");
      out.write("  gap: 0em;\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("  min-width: 950px;/*MODIFIQUE ESTO-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-*/\r\n");
      out.write("  padding:  2em;\r\n");
      out.write("  /* Agregado para dar un poco de espacio interno */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttons-section {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-section {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: flex-start;\r\n");
      out.write("\r\n");
      out.write("  flex-direction: row;\r\n");
      out.write("  gap: 0em;\r\n");
      out.write("  margin-left: 5em;;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".content-extra {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  flex-wrap: nowrap;\r\n");
      out.write("  gap: 1em;\r\n");
      out.write(" /* max-width: 500px;*/\r\n");
      out.write("  padding-top: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".job-card {\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  max-width: 900px;\r\n");
      out.write("\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  transition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".job-card:hover {\r\n");
      out.write("  transform: translateY(-10px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-oferta {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".oferta-image {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 300px;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("  display: block;\r\n");
      out.write("  filter: drop-shadow(10px 10px 10px rgba(0, 0, 0, 0.3));\r\n");
      out.write("  filter: brightness(0.5) blur(2px);\r\n");
      out.write("  transition: filter 0.2s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-oferta img:hover {\r\n");
      out.write("  filter: brightness(1) blur(0px);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-oferta h2 {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 10px;\r\n");
      out.write("  /* Distancia desde la parte superior */\r\n");
      out.write("  left: 10px;\r\n");
      out.write("  /* Distancia desde la izquierda */\r\n");
      out.write("  padding: 0.5em 1em;\r\n");
      out.write("  padding-right: 0;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  font-size: 2em;\r\n");
      out.write("  z-index: 2;\r\n");
      out.write("  /* Asegura que estÃ© encima de la imagen */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".info-oferta ul {\r\n");
      out.write("  padding: 0.5em;\r\n");
      out.write("  list-style: none;\r\n");
      out.write("  gap: 0.2em;\r\n");
      out.write("  display: flex;\r\n");
      out.write("  \r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dflex {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: space-between;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  padding: 0.5em 0;\r\n");
      out.write("  border: 0px;\r\n");
      out.write("  border-bottom: 1px;\r\n");
      out.write("  border-style: solid;\r\n");
      out.write("  border-color: grey;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dflex h3,\r\n");
      out.write(".dflex p {\r\n");
      out.write("  width: 48%;\r\n");
      out.write("  /* para que los tÃ­tulos y los detalles ocupen casi el mismo espacio */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".package-section {\r\n");
      out.write("  display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".package-section,\r\n");
      out.write(".applicants-section {\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  transition: transform 0.3s;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  padding: 1em;\r\n");
      out.write("  min-width: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".package-section:hover,\r\n");
      out.write(".applicants-section:hover {\r\n");
      out.write("  transform: translateY(-10px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".package-section img {\r\n");
      out.write("  margin: 1em;\r\n");
      out.write("  width: 60px;\r\n");
      out.write("  height: 60px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".applicant img {\r\n");
      out.write("  width: 60px;\r\n");
      out.write("  height: 60px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  margin: 0.2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".package-section h3,\r\n");
      out.write(".applicants-section h3 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  margin-bottom: 1em;\r\n");
      out.write("  font-size: 1.5em;\r\n");
      out.write("  color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".applicants-section {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  gap: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".applicant {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  gap: 1em;\r\n");
      out.write("  padding: 0.5em 0;\r\n");
      out.write("  color: black;\r\n");
      out.write("  border-bottom: 1px solid #eee;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".applicant:last-child {\r\n");
      out.write("  border-bottom: none;\r\n");
      out.write("}\r\n");
      out.write(".icon{\r\n");
      out.write("	 width: 24px;\r\n");
      out.write("	 height: 24px;\r\n");
      out.write(" } \r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .main-content {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .left-section {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    /* Usa todo el ancho disponible */\r\n");
      out.write("    margin-left: 0;\r\n");
      out.write("    padding: 1em 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .content-extra {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    /* Usa todo el ancho disponible */\r\n");
      out.write("    margin-left: 0;\r\n");
      out.write("    padding: 1em 0;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .content-section {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 1em;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .job-card {\r\n");
      out.write("    max-width: 100%;\r\n");
      out.write("    /* Usa todo el ancho disponible */\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section {\r\n");
      out.write("    margin-right: 0;\r\n");
      out.write("    padding: 1em;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#frontend-visitante {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: baseline;\r\n");
      out.write("  flex-direction: row;\r\n");
      out.write("  align-items: flex-start;\r\n");
      out.write("  gap: 1em;\r\n");
      out.write("  background-color: #f1f1f1;\r\n");
      out.write("  padding: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".centerText h1 {\r\n");
      out.write("  text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 150px;\r\n");
      out.write("  padding: 12px 20px;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  border: 2px solid #ccc;\r\n");
      out.write("  border-radius: 4px;\r\n");
      out.write("  background-color: #f8f8f8;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  resize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  justify-content: end;\r\n");
      out.write("  gap: 10px;\r\n");
      out.write("  margin: 5px 0 10px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button {\r\n");
      out.write("  padding: 10px 20px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  background-color: #f3f4f6;\r\n");
      out.write("  transition: background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar button, input[type=submit] {\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  border: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  font-size: 16px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  letter-spacing: 0.5px;\r\n");
      out.write("  background-color: #28666e;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("  transition: background-color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-bar button:hover, input[type=submit]:hover {\r\n");
      out.write("  background-color: #1c4c56;\r\n");
      out.write("  transform: translateY(-3px);\r\n");
      out.write("  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".menu-button:hover {\r\n");
      out.write("  background-color: #e1e2e5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-button.active {\r\n");
      out.write("  background-color: #28666e;\r\n");
      out.write("  color: #ffffff;\r\n");
      out.write("}\r\n");
      out.write(".info-oferta {\r\n");
      out.write("    position: relative; /* Posicionamiento relativo para la superposiciÃ³n */\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-container {\r\n");
      out.write("    position: relative; /* Contenedor de la imagen */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".ver-postulacion-btn {\r\n");
      out.write("    position: absolute; /* PosiciÃ³n absoluta para la superposiciÃ³n */\r\n");
      out.write("    top: 100px; /* Espaciado desde la parte superior */\r\n");
      out.write("    left: 80%; /* Centrado horizontal */\r\n");
      out.write("    transform: translateX(-50%); /* Ajuste fino para centrar exactamente */\r\n");
      out.write("    background-color: rgba(40, 102, 110, 0.9); /* Color semi-transparente */\r\n");
      out.write("    color: white; /* Color de texto */\r\n");
      out.write("    padding: 10px 20px; /* Espaciado interno */\r\n");
      out.write("    border: none; /* Sin bordes */\r\n");
      out.write("    border-radius: 5px; /* Bordes redondeados */\r\n");
      out.write("    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3); /* Sombra sutil */\r\n");
      out.write("    cursor: pointer; /* Cursor de mano al pasar por encima */\r\n");
      out.write("    transition: background-color 0.3s; /* TransiciÃ³n suave del color de fondo */\r\n");
      out.write("    transition: font-weight 0.3s; /* TransiciÃ³n suave del color de fondo */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ver-postulacion-btn:hover {\r\n");
      out.write("  background-color: #1e4d56;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nombre-oferta {\r\n");
      out.write("    margin-top: 20px; /* Espacio entre la imagen y el tÃ­tulo */\r\n");
      out.write("    font-size: 1.5em; /* TamaÃ±o del tÃ­tulo */\r\n");
      out.write("    color: #28666e; /* Color del tÃ­tulo */\r\n");
      out.write("    font-weight: 600; /* Negrita para el tÃ­tulo */\r\n");
      out.write("}\r\n");
      out.write(".icon-container{\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	margin-left: 3em;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".icon-container h3{\r\n");
      out.write("	\r\n");
      out.write("	margin-left: 1em;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("}\r\n");
      out.write("a:link, a:visited, a:active, a:hover {\r\n");
      out.write("  color: whitesmoke;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".finalizar-oferta {\r\n");
      out.write("	max-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/header.jsp", out, false);
      out.write("\r\n");
      out.write("    <main id=\"frontend-visitante\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/leftPanel.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"content-section\">\r\n");
      out.write("            <div class=\"main-content\">\r\n");
      out.write("                <div class=\"job-card\">\r\n");
      out.write("                    <div class=\"info-oferta\">\r\n");
      out.write("                        <img class=\"oferta-image\" src=\"/trabajouy/media/images/");
      out.print( (String)((DtOferta) request.getSession().getAttribute("info_oferta")).getUrlFoto() );
      out.write("\" alt=\"foto trabajo\">\r\n");
      out.write("                        <h2>");
      out.print( ((DtOferta)request.getSession().getAttribute("info_oferta")).getNombre() );
      out.write("</h2>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li class=\"dflex\">\r\n");
      out.write("                                <h3>Postulante: </h3>\r\n");
      out.write("                                <p>");
      out.print( ((DtPostulacion)request.getSession().getAttribute("postulacion")).getPostulante() );
      out.write("</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"dflex\">\r\n");
      out.write("                                <h3>CV reducido: </h3>\r\n");
      out.write("                                <textarea readonly>");
      out.print( ((DtPostulacion)request.getSession().getAttribute("postulacion")).getCurriculum() );
      out.write("</textarea>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"dflex\">\r\n");
      out.write("                                <h3>Motivacion: </h3>\r\n");
      out.write("                                    <textarea readonly>");
      out.print( ((DtPostulacion)request.getSession().getAttribute("postulacion")).getDescripcion() );
      out.write("</textarea>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"dflex\">\r\n");
      out.write("                                <h3>Fecha postulacion:</h3>\r\n");
      out.write("                                <p>");
      out.print( ((DtPostulacion)request.getSession().getAttribute("postulacion")).getFechaString() );
      out.write("</p>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
  String nombrePostulante = ((DtPostulacion)request.getSession().getAttribute("postulacion")).getPostulante(); 
                            if(!((DtPostulacion)request.getSession().getAttribute("postulacion")).getUrlVideo().isEmpty()){ 
                                 String url = ((DtPostulacion)request.getSession().getAttribute("postulacion")).getUrlVideo();
                                 
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                               <iframe width=\"800\" height=\"600\" src=\"");
      out.print(url);
      out.write("\" title=\"");
      out.print(nombrePostulante);
      out.write("\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("                            \r\n");
      out.write("                            </li>\r\n");
      out.write("                            ");
} 
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
