/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.11
 * Generated at: 2023-11-09 04:12:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.ofertas;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import net.java.dev.jaxb.array.StringArray;
import java.util.List;
import java.util.Vector;
import java.net.Authenticator.RequestorType;
import com.trabajouy.model.EstadoSesion;
import com.trabajouy.model.EstadoSesion;
import servidor.DtOferta;

public final class ofertasParaPostularse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/styleConsultaOfertas.css", Long.valueOf(1699477528000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.java.dev.jaxb.array.StringArray");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("java.net.Authenticator.RequestorType");
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
    _jspx_imports_classes.add("servidor.DtOferta");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Postularse</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        ");
      out.write("* {\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("  font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("  background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link, a:visited, a:active, a:hover {\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button:hover {\r\n");
      out.write("  cursor: click;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 1rem;\r\n");
      out.write("  margin: 20px;\r\n");
      out.write("      background-color: #f2f2f2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".list-item {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 10px;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-info {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-info img {\r\n");
      out.write("  width: 100px;\r\n");
      out.write("  height: 100px;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write(".list-item {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  transition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-item:hover {\r\n");
      out.write("  box-shadow: 0 6px 25px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  border: 3px solid #28666e;\r\n");
      out.write("  transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-info {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  gap: 20px;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  flex: 3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-info img {\r\n");
      out.write("  max-width: 150px;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-block {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-direction: column;\r\n");
      out.write("  gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-block h2 {\r\n");
      out.write("  font-size: 1.5em;\r\n");
      out.write("  color: #28666e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-block ul {\r\n");
      out.write("  padding-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-buy {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  align-items: center;\r\n");
      out.write("  justify-content: center;\r\n");
      out.write("  flex: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-panel {\r\n");
      out.write("  flex: 2;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-panel h1 {\r\n");
      out.write("  font-size: 2em;\r\n");
      out.write("  margin-bottom: 20px;\r\n");
      out.write("  color: #28666e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center-panel {\r\n");
      out.write("  padding: 20px;\r\n");
      out.write("  background-color: #f7f9fa;\r\n");
      out.write("  border-radius: 10px;\r\n");
      out.write("  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 768px) {\r\n");
      out.write("  .main {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .left-panel,\r\n");
      out.write("  .center-panel {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .list-item {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .list-info {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .list-buy {\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  header {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .search-box {\r\n");
      out.write("    width: 90%;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section {\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section div {\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .profile-section button {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".button-view {\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  font-size: larger;\r\n");
      out.write("  width: 140px;\r\n");
      out.write("  padding: 10px 15px;\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("  background-color: #28666e;\r\n");
      out.write("  color: #f4f4f4;\r\n");
      out.write("  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  transition: transform 0.2s ease, box-shadow 0.2s ease;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  border-style: none;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".button-view:hover {\r\n");
      out.write("  transform: translateY(-5px);\r\n");
      out.write("  box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filters-panel {\r\n");
      out.write("  margin-bottom: 10px;\r\n");
      out.write("}");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/header.jsp", out, false);
      out.write("\r\n");
      out.write("   <div class=\"main\">\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/leftPanel.jsp", out, false);
      out.write("\r\n");
      out.write("		<div class=\"center-panel\">\r\n");
      out.write("		<h1>Postularse</h1>\r\n");
      out.write("		<div class=\"filters-panel\">\r\n");
      out.write("		            <form action=\"ofertas-postularse\" method=\"GET\">\r\n");
      out.write("                <label for=\"select-empresa\">Empresa: </label>\r\n");
      out.write("                <select id=\"select-empresa\" name=\"opcion\">\r\n");
      out.write("                    <option id=\"optionE-none\" selected></option>\r\n");
      out.write("                    ");
 if (request.getSession().getAttribute("nickEmpresas_sesion") != null) {
                    	List<String> info = (List<String>) request.getSession().getAttribute("nickEmpresas_sesion");
              
                        		for (String nick : info ) {
                        
      out.write("\r\n");
      out.write("                            <option id=\"optionE-");
      out.print( nick );
      out.write('"');
      out.write('>');
      out.print( nick );
      out.write("</option>\r\n");
      out.write("                        ");

                        	}
                        }
                        
      out.write("             \r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"submit\" value=\"Enviar\">\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <form action=\"ofertas-postularse\" method=\"GET\">\r\n");
      out.write("                <label for=\"select-keyword\">Keyword: </label>\r\n");
      out.write("                <select id=\"select-keyword\" name=\"opcionK\">\r\n");
      out.write("                <option id=\"optionK-none\" selected></option>\r\n");
      out.write("                ");
 if (request.getSession().getAttribute("keywords_leftpanel") != null) {
                	List<String> info = (List<String>) request.getSession().getAttribute("keywords_leftpanel");
                	 
                	
                	for (String keyword : info ) {
                        
      out.write("\r\n");
      out.write("                            <option id=\"optionK-");
      out.print( keyword );
      out.write('"');
      out.write('>');
      out.print( keyword );
      out.write("</option>\r\n");
      out.write("                        ");

                        	}
                        }
                        
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                <input type=\"submit\" value=\"Enviar\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("             ");
 
             List<DtOferta> info = (List<DtOferta>) request.getSession().getAttribute("ofertas_sin_postularse");
		      if (info != null && !info.isEmpty()) {
		          for (DtOferta oferta : info) {
	   
      out.write("\r\n");
      out.write("	    <div class=\"list-item\">\r\n");
      out.write("	        <div class=\"list-info\">\r\n");
      out.write("	        <img src=\"/trabajouy/media/images/");
      out.print( oferta.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("            <div class=\"list-block\">\r\n");
      out.write("                <h2>");
      out.print( oferta.getNombre() );
      out.write("</h2> \r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p>");
      out.print( oferta.getDescripcion() );
      out.write("</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <form action=\"/trabajouy/ofertas-postularse\" method=\"post\" class=\"list-buy\">\r\n");
      out.write("	        	<button class=\"button-view\" name=\"postularse\" value=\"");
      out.print( oferta.getNombre());
      out.write("\" id=\"view-basico\">Postularse</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    ");
 
	        }
	    } 
	    
      out.write("\r\n");
      out.write("            \r\n");
      out.write("	   ");
 
	    	Vector<DtOferta> infoE = (Vector<DtOferta>) request.getSession().getAttribute("ofertas_empresa");
		      if (infoE != null && !infoE.isEmpty()) {
		          for (DtOferta oferta : infoE) {
	   
      out.write("\r\n");
      out.write("	    <div class=\"list-item\">\r\n");
      out.write("	        <div class=\"list-info\">\r\n");
      out.write("	        <img src=\"/trabajouy/media/images/");
      out.print( oferta.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("            <div class=\"list-block\">\r\n");
      out.write("                <h2>");
      out.print( oferta.getNombre() );
      out.write("</h2> \r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p>");
      out.print( oferta.getDescripcion() );
      out.write("</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <form action=\"/trabajouy/ofertas-postularse\" method=\"post\" class=\"list-buy\">\r\n");
      out.write("	        	<button class=\"button-view\" name=\"postularse\" value=\"");
      out.print( oferta.getNombre());
      out.write("\" id=\"view-basico\">Postularse</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    ");
 
	        }
	    } 
	    
      out.write("\r\n");
      out.write("	    \r\n");
      out.write("	    ");
 
	    	Vector<DtOferta> infoK = (Vector<DtOferta>) request.getSession().getAttribute("ofertas_keywords");
		      if (infoK != null && !infoK.isEmpty()) {
		          for (DtOferta oferta : infoK) {
	   
      out.write("\r\n");
      out.write("	    <div class=\"list-item\">\r\n");
      out.write("	        <div class=\"list-info\">\r\n");
      out.write("	        <img src=\"/trabajouy/media/images/");
      out.print( oferta.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\r\n");
      out.write("            <div class=\"list-block\">\r\n");
      out.write("                <h2>");
      out.print( oferta.getNombre() );
      out.write("</h2> \r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <p>");
      out.print( oferta.getDescripcion() );
      out.write("</p>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <form action=\"/trabajouy/ofertas-postularse\" method=\"post\" class=\"list-buy\">\r\n");
      out.write("	        	<button class=\"button-view\" name=\"postularse\" value=\"");
      out.print( oferta.getNombre());
      out.write("\" id=\"view-basico\">Postularse</button>\r\n");
      out.write("	        </form>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    ");
 
	        }
	    } 
	    
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
