/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-14 01:40:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.usuarios;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import servidor.DtUsuarioSeguidores;
import servidor.DtPostulacionArray;
import java.util.List;
import servidor.DtCompraPaqueteArray;
import java.io.ObjectInputStream.GetField;
import com.trabajouy.model.EstadoSesion;
import java.util.Date;
import java.util.Vector;
import java.util.Map;
import servidor.DtUsuario;
import servidor.DtEmpresa;
import servidor.DtPostulante;
import servidor.DtPublicar;
import servidor.DtPostulacion;
import servidor.DtCompraPaquete;

public final class perfil_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/media/styles/consultarPerfil.css", Long.valueOf(1699925636000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("servidor.DtEmpresa");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("servidor.DtPostulante");
    _jspx_imports_classes.add("servidor.DtCompraPaqueteArray");
    _jspx_imports_classes.add("servidor.DtUsuarioSeguidores");
    _jspx_imports_classes.add("com.trabajouy.model.EstadoSesion");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("servidor.DtCompraPaquete");
    _jspx_imports_classes.add("java.util.Vector");
    _jspx_imports_classes.add("servidor.DtPublicar");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("servidor.DtPostulacion");
    _jspx_imports_classes.add("servidor.DtPostulacionArray");
    _jspx_imports_classes.add("servidor.DtUsuario");
    _jspx_imports_classes.add("java.io.ObjectInputStream.GetField");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Perfil</title>\n");
      out.write("    <style>\n");
      out.write("        ");
      out.write("\n");
      out.write("\n");
      out.write("a:link, a:visited, a:active, a:hover {\n");
      out.write("    color: black;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main, .general-info, .menu-bar {\n");
      out.write("    display: flex;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".main{\n");
      out.write("   justify-content: baseline;\n");
      out.write("   padding: 1.5em;\n");
      out.write("   gap: 6em;\n");
      out.write("   background-color: #f2f2f2;\n");
      out.write("}\n");
      out.write(".menu-bar button {\n");
      out.write("    padding: 10px 15px;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    font-size: 16px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    letter-spacing: 0.5px;\n");
      out.write("    background-color: #28666e;\n");
      out.write("    color: #ffffff;\n");
      out.write("    transition: background-color 0.3s ease;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".info-container li:hover {\n");
      out.write("    transition: 100ms;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#profile-photo-no-header {\n");
      out.write("    border: 3px solid #28666e;\n");
      out.write("    border-radius: 50%;\n");
      out.write("    width: 150px;\n");
      out.write("    height: 150px;\n");
      out.write("    margin: 1em;\n");
      out.write("    transition: transform 0.3s ease;\n");
      out.write("}\n");
      out.write("#profile-photo-no-header:hover {\n");
      out.write("    transform: translateY(-5px);\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".info-container {\n");
      out.write("    width: 800px;\n");
      out.write("    background-color: #ffffff;\n");
      out.write("    font-size: large;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".general-info .name-and-more {\n");
      out.write("    margin-left: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-bar .derecha {\n");
      out.write("    justify-content: flex-end;\n");
      out.write("    width: 100%;\n");
      out.write("    padding-right: 5px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".info-container ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    padding-left: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".name-and-more h1, .name-and-more h2, .name-and-more h3, .center-panel .name-and-more h1, .center-panel .name-and-more h2, .center-panel .name-and-more h3 {\n");
      out.write("    margin: 5px 0;\n");
      out.write("    color: #28666e;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-bar button:hover {\n");
      out.write("    background-color: #1c4c56;\n");
      out.write("    transform: translateY(-3px);\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.15);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".detailed-info {\n");
      out.write("    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.1);\n");
      out.write("    border-radius: 10px;\n");
      out.write("    padding: 20px;\n");
      out.write("    background-color: #ffffff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-bar {\n");
      out.write("    justify-content: baseline;\n");
      out.write("    gap: 10px;\n");
      out.write("    margin-bottom: 20px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-button {\n");
      out.write("    padding: 10px 20px;\n");
      out.write("    cursor: pointer;\n");
      out.write("    border: none;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    background-color: #f3f4f6;\n");
      out.write("    transition: background-color 0.3s;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-button:hover {\n");
      out.write("    background-color: #e1e2e5;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".menu-button.active {\n");
      out.write("    background-color: #28666e;\n");
      out.write("    color: #ffffff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".right-aligned {\n");
      out.write("    margin-left: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".info-container li p {\n");
      out.write("    margin: 5px 0;\n");
      out.write("    padding: 10px;\n");
      out.write("    border-bottom: 1px solid #f1f1f1;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".info-container li:last-child p {\n");
      out.write("    border-bottom: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".list-item {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 10px;\n");
      out.write("    padding: 10px;\n");
      out.write("    background-color: #fff;\n");
      out.write("    box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\n");
      out.write("    margin-bottom: 10px;\n");
      out.write("    width: 100%;\n");
      out.write("    border-radius: 5px;\n");
      out.write("    transition: transform 0.3s;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-info {\n");
      out.write("    display: flex;\n");
      out.write("    gap: 20px;\n");
      out.write("    padding: 10px;\n");
      out.write("    flex: 3;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-info img {\n");
      out.write("    width: 100px;\n");
      out.write("    height: 100px;\n");
      out.write("    object-fit: cover;\n");
      out.write("    max-width: 150px;\n");
      out.write("    border-radius: 5px;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-item:hover {\n");
      out.write("    box-shadow: 0 6px 25px rgba(0, 0, 0, 0.15);\n");
      out.write("    border: 3px solid #28666e;\n");
      out.write("    transform: scale(1.05);\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  .list-block {\n");
      out.write("    display: flex;\n");
      out.write("    flex-direction: column;\n");
      out.write("    gap: 10px;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-block h2 {\n");
      out.write("    font-size: 1.5em;\n");
      out.write("    color: #28666e;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-block ul {\n");
      out.write("    padding-left: 20px;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  .list-buy {\n");
      out.write("    display: flex;\n");
      out.write("    align-items: center;\n");
      out.write("    justify-content: center;\n");
      out.write("    flex: 1;\n");
      out.write("  }\n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("  \n");
      out.write("\n");
      out.write("\n");
      out.write("        h1 img {\n");
      out.write("            vertical-align: middle; \n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/header.jsp", out, false);
      out.write("\n");
      out.write("   	\n");
      out.write("   <div class=\"main\">\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/template/leftPanel.jsp", out, false);
      out.write("\n");
      out.write("        <div class=\"center-panel\">\n");
      out.write("            <div class=\"general-info\">\n");
      out.write("                <img id=\"profile-photo-no-header\" src=\"/web/media/images/");
      out.print( (String)((DtUsuario) request.getSession().getAttribute("info_perfil")).getFoto() );
      out.write("\"/>\n");
      out.write("                <div class=\"name-and-more\">\n");
      out.write("                    <h1>");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getNombre() +" "+ ((DtUsuario) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("\n");
      out.write("                     ");

                     		DtUsuario user = (DtUsuario) request.getSession().getAttribute("info_perfil");
		                	servidor.PublicadorService service = new servidor.PublicadorService();
		            		servidor.Publicador portPublicador = service.getPublicadorPort();
		        			if ((EstadoSesion) request.getSession().getAttribute("estado_sesion") == EstadoSesion.POSTULANTE || (EstadoSesion) request.getSession().getAttribute("estado_sesion") == EstadoSesion.EMPRESA)  {
		        				if(!((String) request.getSession().getAttribute("nickname_sesion")).equals(((DtUsuario) request.getSession().getAttribute("info_perfil")).getNickname())) {
		        					if(portPublicador.sigueAUsuario((String) request.getSession().getAttribute("nickname_sesion"), user.getNickname())) {
		        		
      out.write("\n");
      out.write("		        				<a href=\"/web/perfil?unfollow=");
      out.print( user.getNickname());
      out.write("&usuarioB=");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getNickname() );
      out.write("\"><img style=\"width:30px; height:30px;\" src=\"/web/media/images/unfollow.png\"/></a>\n");
      out.write("		        		");

		        					} else {
		        		
      out.write("\n");
      out.write("		        				<a href=\"/web/perfil?follow=");
      out.print( user.getNickname());
      out.write("&usuarioB=");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getNickname() );
      out.write("\"><img style=\"width:30px; height:30px;\" src=\"/web/media/images/follow.png\"/></a>\n");
      out.write("		        		");
			}
		        				}
		        			}
		        		
      out.write(" \n");
      out.write("                    </h1>\n");
      out.write("                    <h2>");
      out.print( ((DtUsuario) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</h2>\n");
      out.write("                    <h3>Último Ingreso: <span id=\"last-date\">");
      out.print( new Date() );
      out.write("</span></h3>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"detailed-info\">\n");
      out.write("            ");

            	if (request.getSession().getAttribute("info_perfil") instanceof DtEmpresa) {
            
      out.write("\n");
      out.write("            	<div class=\"menu-bar\">\n");
      out.write("                    <button id=\"profile-button\">Perfil</button>\n");
      out.write("                     <button id=\"seguidos-button\" >Seguidos</button>\n");
      out.write("                    <button id=\"seguidores-button\">Seguidores</button>\n");
      out.write("                    <button id=\"offers-button\" style=\"visibility:hidden;\">Ofertas Laborales</button>\n");
      out.write("                    <button id=\"packages-button\" style=\"visibility:hidden;\">Paquetes</button>\n");
      out.write("                    <a href=\"modificarUsuario\" style=\"visibility:hidden;\" id=\"edit-button\"><button class=\"menu-button right-aligned\">Editar</button></a>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            ");

            	}else {
            		if (request.getSession().getAttribute("info_perfil") instanceof DtPostulante) {
            
      out.write("\n");
      out.write("                <div class=\"menu-bar\">\n");
      out.write("                    <button class=\"menu-button active\" id=\"profile-button\">Perfil</button>\n");
      out.write("                    <button id=\"seguidos-button\" >Seguidos</button>\n");
      out.write("                    <button id=\"seguidores-button\">Seguidores</button>\n");
      out.write("                    <button class=\"menu-button\" id=\"postulations-button\" style=\"visibility:hidden;\">Postulaciones</button>\n");
      out.write("                    <a href=\"modificarUsuario\" style=\"visibility:hidden;\" id=\"edit-button\"><button class=\"menu-button right-aligned\">Editar</button></a>\n");
      out.write("                </div>\n");
      out.write("            ");

            		}
            	}
            
      out.write("\n");
      out.write("                <div id=\"info-container\" class=\"info-container\">\n");
      out.write("                ");

            		if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))) {
            	
      out.write("\n");
      out.write("                    <ul>\n");
      out.write("                        <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( (String) request.getSession().getAttribute("consultar_perfil") );
      out.write("</span></p></li>\n");
      out.write("                        <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\n");
      out.write("	                </ul>\n");
      out.write("                ");

            		}else {
            		    
            			if (portPublicador.esPostulante((String) request.getSession().getAttribute("consultar_perfil"))) {
            	
      out.write("\n");
      out.write("	            	<ul>\n");
      out.write("                        <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( (String) request.getSession().getAttribute("consultar_perfil") );
      out.write("</span></p></li>\n");
      out.write("                        <li><p><b>Nombre: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Apellido: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Email: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Fecha de Nacimiento: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getFechaB() );
      out.write("</p></li>\n");
      out.write("                        <li><p><b>Nacionalidad: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNacionalidad() );
      out.write("</p></li>\n");
      out.write("	                </ul>\n");
      out.write("	            ");

            			}
            		}
            	
      out.write("\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("	<script>\n");
      out.write("	    ");

               String consultarPerfil = (String) request.getSession().getAttribute("consultar_perfil");
	           String nickSesion = (String) request.getSession().getAttribute("nickname_sesion");
	    
	       
	     	if (nickSesion !=null && nickSesion.equals(consultarPerfil)) {
	     		if (request.getSession().getAttribute("info_perfil") instanceof DtPostulante) {
    	
      out.write("\n");
      out.write("		    const postulationsButton = document.getElementById(\"postulations-button\");\n");
      out.write("		    const infoContainer = document.getElementById(\"info-container\");\n");
      out.write("		    const profileButton = document.getElementById(\"profile-button\");\n");
      out.write("		    const seguidoresButton = document.getElementById(\"seguidores-button\");\n");
      out.write("	        const seguidosButton = document.getElementById(\"seguidos-button\");\n");
      out.write("	        const editButton = document.getElementById(\"edit-button\");\n");
      out.write("		    editButton.style.visibility = \"visible\";\n");
      out.write("		    postulationsButton.style.visibility = \"visible\";\n");
      out.write("		    seguidosButton.style.visibility=\"visible\";\n");
      out.write("		    seguidoresButton.style.visibility=\"visible\";\n");
      out.write("		    \n");
      out.write("		    profileButton.addEventListener(\"click\", () => {\n");
      out.write("		    	editButton.disabled = false;\n");
      out.write("		    	editButton.style.visibility= \"visible\";\n");
      out.write("		    	infoContainer.innerHTML = `<ul>\n");
      out.write("                    <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( request.getSession().getAttribute("nickname_sesion") );
      out.write("</span></p></li>\n");
      out.write("                    <li><p><b>Nombre: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Apellido: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Email: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Fecha de Nacimiento: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getFechaB() );
      out.write("</p></li>\n");
      out.write("                </ul>`;\n");
      out.write("		    })\n");
      out.write("		     seguidoresButton.addEventListener(\"click\", () => {\n");
      out.write("		     	editButton.style.visibility= \"hidden\";\n");
      out.write("		    	editButton.disabled = true;\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publiI = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publiI.getSeguidores()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("	                  \n");
      out.write("	            seguidosButton.addEventListener(\"click\", () => {\n");
      out.write("	            	editButton.style.visibility= \"hidden\";\n");
      out.write("			    	editButton.disabled = true;\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publit = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publit.getSeguidos()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("		\n");
      out.write("		    postulationsButton.addEventListener(\"click\", () => {\n");
      out.write("		    	editButton.style.visibility= \"hidden\";\n");
      out.write("		    	editButton.disabled = true;\n");
      out.write("		    	infoContainer.innerHTML = `\n");
      out.write("		        ");
 
		        DtPostulacionArray postuArray = (DtPostulacionArray) request.getSession().getAttribute("postulaciones_perfil");     
		    	List<DtPostulacion> info =	postuArray.getItem();
		        for (DtPostulacion postu : info) {
		       
		        		
      out.write("\n");
      out.write("		        	<ul>\n");
      out.write("                         <li>\n");
      out.write("                         <a href=\"info-oferta?oferta=");
      out.print( postu.getOferta() );
      out.write("\">\n");
      out.write("	                       		<div class=\"list-item\">\n");
      out.write("	                       			 <div class=\"list-info\">\n");
      out.write("	                       			 <img src=\"/web/media/images/");
      out.print( postu.getUrlfoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                           			<div class=\"list-block\">\n");
      out.write("	                               			<h2>");
      out.print( postu.getOferta());
      out.write("</h2>\n");
      out.write("	                               			<ul>\n");
      out.write("	                                   			<li><b>Fecha de Postulación: </b>");
      out.print(postu.getFechaString());
      out.write("</li>\n");
      out.write("	                               			</ul>\n");
      out.write("	                           			</div>\n");
      out.write("	                       			</div>\n");
      out.write("	                   			</div>\n");
      out.write("                   			</a>\n");
      out.write("                     	</li>\n");
      out.write("                     </ul>\n");
      out.write("                ");

     				}
                
      out.write("\n");
      out.write("		    `;}) \n");
      out.write("	    ");

        	} else {
        		
        			
        		if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))) {
        
      out.write("\n");
      out.write("	        const offersButton = document.getElementById(\"offers-button\");\n");
      out.write("	        const infoContainer = document.getElementById(\"info-container\");\n");
      out.write("	        const profileButton = document.getElementById(\"profile-button\");\n");
      out.write("	        const seguidoresButton = document.getElementById(\"seguidores-button\");\n");
      out.write("	        const seguidosButton = document.getElementById(\"seguidos-button\");\n");
      out.write("	        const packagesButton = document.getElementById(\"packages-button\");\n");
      out.write("	        const editButton = document.getElementById(\"edit-button\");\n");
      out.write("	        \n");
      out.write("	        seguidoresButton.style.visibility = \"visible\";\n");
      out.write("	        seguidosButton.style.visibility = \"visible\";\n");
      out.write("	        editButton.style.visibility = \"visible\";\n");
      out.write("	        offersButton.style.visibility = \"visible\";\n");
      out.write("	        packagesButton.style.visibility = \"visible\";\n");
      out.write("	\n");
      out.write("	        profileButton.addEventListener(\"click\", () => {\n");
      out.write("	        	editButton.style.visibility = \"visible\";\n");
      out.write("	        	infoContainer.innerHTML = `<ul>\n");
      out.write("								        		<li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( request.getSession().getAttribute("nickname_sesion") );
      out.write("</span></p></li>\n");
      out.write("							                    <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("							                    <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("							                    <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("							                    <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\n");
      out.write("							                    <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\n");
      out.write("	                                        </ul>`;\n");
      out.write("	        })\n");
      out.write("	\n");
      out.write("	        seguidoresButton.addEventListener(\"click\", () => {\n");
      out.write("	            editButton.style.visibility = \"hidden\";\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publiI = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publiI.getSeguidores()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                    		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("	                  \n");
      out.write("	            seguidosButton.addEventListener(\"click\", () => {\n");
      out.write("	            editButton.style.visibility = \"hidden\";\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publit = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publit.getSeguidos()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("	            \n");
      out.write("	            \n");
      out.write("	            \n");
      out.write("	             offersButton.addEventListener(\"click\", () => {\n");
      out.write("	            editButton.style.visibility = \"hidden\";\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
		        	for (DtPublicar publi : (Vector<DtPublicar>)request.getSession().getAttribute("publicaciones_perfil")) {
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"info-oferta?oferta=");
      out.print(publi.getOferta() );
      out.write("&estado=");
      out.print( publi.getEstado() );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print( publi.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi.getOferta());
      out.write("</h2>\n");
      out.write("	                                                        		<ul>\n");
      out.write("	                                                            		<li><b>Estado: </b>");
      out.print( publi.getEstado());
      out.write("</li>\n");
      out.write("	                                                        		</ul>\n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("	\n");
      out.write("	        packagesButton.addEventListener(\"click\", () => {\n");
      out.write("	            editButton.style.visibility = \"hidden\";\n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	            DtCompraPaqueteArray mapaP = (DtCompraPaqueteArray) request.getSession().getAttribute("paquetes_comprados_perfil");
	            List<DtCompraPaquete> info = mapaP.getItem();
		        	for (DtCompraPaquete paquete : info) {
		         
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"info-paquete?nombre=");
      out.print( paquete.getPaquete() );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(  paquete.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( paquete.getPaquete());
      out.write("</h2>\n");
      out.write("	                                                        		<ul>\n");
      out.write("	                                                            		<li><b>Fecha de Compra: </b>");
      out.print( paquete.getFecha());
      out.write("</li>\n");
      out.write("	                                                            		<li><b>Fecha de Vencimiento: </b>");
      out.print( paquete.getVencimiento());
      out.write("</li>\n");
      out.write("	                                                        		</ul>\n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	          ");

		        	}
	          
      out.write("                              \n");
      out.write("	          `;})\n");
      out.write("        ");

        			}
        		}
	     	} else if (portPublicador.esEmpresa((String) request.getSession().getAttribute("consultar_perfil"))){
	     		 
      out.write("\n");
      out.write("		           const offersButton = document.getElementById(\"offers-button\");\n");
      out.write("			       const infoContainer = document.getElementById(\"info-container\");\n");
      out.write("			       const profileButton = document.getElementById(\"profile-button\");\n");
      out.write("			       const seguidoresButton = document.getElementById(\"seguidores-button\");\n");
      out.write("			       const seguidosButton = document.getElementById(\"seguidos-button\");\n");
      out.write("			       \n");
      out.write("			       offersButton.style.visibility = \"visible\";\n");
      out.write("			       profileButton.addEventListener(\"click\", () => {\n");
      out.write("			        	infoContainer.innerHTML = `<ul>\n");
      out.write("										        		<li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNickname() );
      out.write("</span></p></li>\n");
      out.write("									                    <li><p><b>Nombre: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("									                    <li><p><b>Apellido: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("									                    <li><p><b>Email: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("									                    <li><p><b>Sitio Web: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getLink() );
      out.write("</p></li>\n");
      out.write("									                    <li><p><b>Descripción: </b>");
      out.print( ((DtEmpresa) request.getSession().getAttribute("info_perfil")).getDescripcion() );
      out.write("</p></li>\n");
      out.write("			                                        </ul>`;\n");
      out.write("			        })\n");
      out.write("			        \n");
      out.write("			       offersButton.addEventListener(\"click\", () => {\n");
      out.write("			            infoContainer.innerHTML = `\n");
      out.write("			            ");
 
				        	for (DtPublicar publi : (Vector<DtPublicar>)request.getSession().getAttribute("publicacionesConfirmadas_perfil")) {
				       
				        		
      out.write("\n");
      out.write("			            							<ul>\n");
      out.write("			                                            <li>\n");
      out.write("			                                            <a href=\"info-oferta?oferta=");
      out.print( publi.getOferta());
      out.write("&estado=");
      out.print( publi.getEstado() );
      out.write("\">\n");
      out.write("			                                            		<div class=\"list-item\">\n");
      out.write("			                                                		<div class=\"list-info\">\n");
      out.write("			                                                		<img src=\"/web/media/images/");
      out.print( publi.getUrlFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("			                                                    		<div class=\"list-block\">\n");
      out.write("			                                                        		<h2>");
      out.print( publi.getOferta());
      out.write("</h2>\n");
      out.write("			                                                        		<ul>\n");
      out.write("			                                                            		<li><b>Estado: </b>");
      out.print( publi.getEstado());
      out.write("</li>\n");
      out.write("			                                                        		</ul>\n");
      out.write("			                                                    		</div>\n");
      out.write("			                                                		</div>\n");
      out.write("			                                            		</div>\n");
      out.write("			                                            	</a>\n");
      out.write("			                                        	</li>\n");
      out.write("			                                        </ul>\n");
      out.write("			            ");

		     				}
		                
      out.write("                              \n");
      out.write("			            `;})\n");
      out.write("			            \n");
      out.write("			   seguidoresButton.addEventListener(\"click\", () => {\n");
      out.write("	           \n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publiI = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publiI.getSeguidores()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("	                  \n");
      out.write("	            seguidosButton.addEventListener(\"click\", () => {\n");
      out.write("	            \n");
      out.write("	            infoContainer.innerHTML = `\n");
      out.write("	            ");
 
	           DtUsuario publit = (DtUsuario) request.getSession().getAttribute("info_perfil");
	            
	            
		        	for (String publi : publit.getSeguidos()) {
		        		
		            
		        		
      out.write("\n");
      out.write("	            							<ul>\n");
      out.write("	                                            <li>\n");
      out.write("	                                            <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("	                                            		<div class=\"list-item\">\n");
      out.write("	                                                		<div class=\"list-info\">\n");
      out.write("	                                                		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("	                                                    		<div class=\"list-block\">\n");
      out.write("	                                                        		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("	                                                     \n");
      out.write("	                                                    		</div>\n");
      out.write("	                                                		</div>\n");
      out.write("	                                            		</div>\n");
      out.write("	                                            	</a>\n");
      out.write("	                                        	</li>\n");
      out.write("	                                        </ul>\n");
      out.write("	            ");

     				}
                
      out.write("                              \n");
      out.write("	            `;})\n");
      out.write("			            \n");
      out.write("			       \n");
      out.write("			       ");
 
	     	} else if (portPublicador.esPostulante((String) request.getSession().getAttribute("consultar_perfil"))){
	     		
        
      out.write("\n");
      out.write("         const seguidoresButton = document.getElementById(\"seguidores-button\");\n");
      out.write("	     const seguidosButton = document.getElementById(\"seguidos-button\");\n");
      out.write("	     const infoContainer = document.getElementById(\"info-container\");\n");
      out.write("	     const profileButton = document.getElementById(\"profile-button\");\n");
      out.write("        \n");
      out.write(" 	   \n");
      out.write("	     \n");
      out.write("	     \n");
      out.write("	     \n");
      out.write("	     \n");
      out.write("	       profileButton.addEventListener(\"click\", () => {\n");
      out.write("	        	infoContainer.innerHTML = `<ul>\n");
      out.write("                    <li><p><b>Nickname: </b><span id=\"profile-nickname\">");
      out.print( (String) request.getSession().getAttribute("consultar_perfil") );
      out.write("</span></p></li>\n");
      out.write("                    <li><p><b>Nombre: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNombre() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Apellido: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getApellido() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Email: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getEmail() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Fecha de Nacimiento: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getFechaB() );
      out.write("</p></li>\n");
      out.write("                    <li><p><b>Nacionalidad: </b>");
      out.print( ((DtPostulante) request.getSession().getAttribute("info_perfil")).getNacionalidad() );
      out.write("</p></li>\n");
      out.write("                </ul>`;\n");
      out.write("	        })\n");
      out.write("	     \n");
      out.write("	     seguidoresButton.addEventListener(\"click\", () => {\n");
      out.write("           \n");
      out.write("           infoContainer.innerHTML = `\n");
      out.write("           ");
 
          DtUsuario publiI = (DtUsuario) request.getSession().getAttribute("info_perfil");
           
           
           for (String publi : publiI.getSeguidores()) {
	        		
	            
	        		
      out.write("\n");
      out.write("           							<ul>\n");
      out.write("                                           <li>\n");
      out.write("                                           <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("                                           		<div class=\"list-item\">\n");
      out.write("                                               		<div class=\"list-info\">\n");
      out.write("                                               		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("                                                   		<div class=\"list-block\">\n");
      out.write("                                                   		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("                                                    \n");
      out.write("                                                   		</div>\n");
      out.write("                                               		</div>\n");
      out.write("                                           		</div>\n");
      out.write("                                           	</a>\n");
      out.write("                                       	</li>\n");
      out.write("                                       </ul>\n");
      out.write("           ");

				}
           
      out.write("                              \n");
      out.write("           `;})\n");
      out.write("                 \n");
      out.write("           seguidosButton.addEventListener(\"click\", () => {\n");
      out.write("           \n");
      out.write("           infoContainer.innerHTML = `\n");
      out.write("           ");
 
          DtUsuario publit = (DtUsuario) request.getSession().getAttribute("info_perfil");
           
           
	        	for (String publi : publit.getSeguidos()) {
	        		
	            
	        		
      out.write("\n");
      out.write("           							<ul>\n");
      out.write("                                           <li>\n");
      out.write("                                           <a href=\"/web/perfil?usuarioB=");
      out.print(publi );
      out.write("\">\n");
      out.write("                                           		<div class=\"list-item\">\n");
      out.write("                                               		<div class=\"list-info\">\n");
      out.write("                                               		<img src=\"/web/media/images/");
      out.print(portPublicador.getUsuario(publi).getFoto() );
      out.write("\" alt=\"Imagen de la oferta\" />\n");
      out.write("                                                   		<div class=\"list-block\">\n");
      out.write("                                                       		<h2>");
      out.print( publi);
      out.write("</h2>\n");
      out.write("                                                    \n");
      out.write("                                                   		</div>\n");
      out.write("                                               		</div>\n");
      out.write("                                           		</div>\n");
      out.write("                                           	</a>\n");
      out.write("                                       	</li>\n");
      out.write("                                       </ul>\n");
      out.write("           ");

				}
           
      out.write("                              \n");
      out.write("           `;})\n");
      out.write("           \n");
      out.write("           ");

			}
       
      out.write(" \n");
      out.write("      \n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
