
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "KeywordRepetida", targetNamespace = "http://Servidor/")
public class KeywordRepetida_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private KeywordRepetida faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public KeywordRepetida_Exception(String message, KeywordRepetida faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public KeywordRepetida_Exception(String message, KeywordRepetida faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.KeywordRepetida
     */
    public KeywordRepetida getFaultInfo() {
        return faultInfo;
    }

}
