
package servidor;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import net.java.dev.jaxb.array.StringArray;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Publicador", targetNamespace = "http://Servidor/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    servidor.ObjectFactory.class,
    net.java.dev.jaxb.array.ObjectFactory.class
})
public interface Publicador {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @throws UsuarioEmailRepetido_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/modificarPostulanteRequest", output = "http://Servidor/Publicador/modificarPostulanteResponse", fault = {
        @FaultAction(className = UsuarioEmailRepetido_Exception.class, value = "http://Servidor/Publicador/modificarPostulante/Fault/UsuarioEmailRepetido")
    })
    public void modificarPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6)
        throws UsuarioEmailRepetido_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtUsuario
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getUsuarioRequest", output = "http://Servidor/Publicador/getUsuarioResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/getUsuario/Fault/UsuarioNoExisteException")
    })
    public DtUsuario getUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws UsuarioEmailRepetido_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/modificarEmpresaRequest", output = "http://Servidor/Publicador/modificarEmpresaResponse", fault = {
        @FaultAction(className = UsuarioEmailRepetido_Exception.class, value = "http://Servidor/Publicador/modificarEmpresa/Fault/UsuarioEmailRepetido")
    })
    public void modificarEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws UsuarioEmailRepetido_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/listarEmpresasRequest", output = "http://Servidor/Publicador/listarEmpresasResponse")
    public StringArray listarEmpresas();

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getNombresOfertasRequest", output = "http://Servidor/Publicador/getNombresOfertasResponse")
    public StringArray getNombresOfertas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/altaEmpresaRequest", output = "http://Servidor/Publicador/altaEmpresaResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://Servidor/Publicador/altaEmpresa/Fault/UsuarioRepetidoException")
    })
    public void altaEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @return
     *     returns servidor.DtUsuarioArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getUsuariosRequest", output = "http://Servidor/Publicador/getUsuariosResponse")
    public DtUsuarioArray getUsuarios();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtCompraPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getCompraPaquetesEmpresaRequest", output = "http://Servidor/Publicador/getCompraPaquetesEmpresaResponse")
    public DtCompraPaqueteArray getCompraPaquetesEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws OfertaNoExisteException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod(operationName = "PostulacionOfertaLaboral")
    @Action(input = "http://Servidor/Publicador/PostulacionOfertaLaboralRequest", output = "http://Servidor/Publicador/PostulacionOfertaLaboralResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/PostulacionOfertaLaboral/Fault/UsuarioNoExisteException"),
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/PostulacionOfertaLaboral/Fault/OfertaNoExisteException")
    })
    public void postulacionOfertaLaboral(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws OfertaNoExisteException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/infoPaquetesNoCompradosRequest", output = "http://Servidor/Publicador/infoPaquetesNoCompradosResponse")
    public DtPaqueteArray infoPaquetesNoComprados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoOfertaBasicoRequest", output = "http://Servidor/Publicador/getInfoOfertaBasicoResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getInfoOfertaBasico/Fault/OfertaNoExisteException")
    })
    public String getInfoOfertaBasico(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getNombreOfertasConfirmadasRequest", output = "http://Servidor/Publicador/getNombreOfertasConfirmadasResponse")
    public StringArray getNombreOfertasConfirmadas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoPostulantesStringRequest", output = "http://Servidor/Publicador/getInfoPostulantesStringResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getInfoPostulantesString/Fault/OfertaNoExisteException")
    })
    public String getInfoPostulantesString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoOfertaStringRequest", output = "http://Servidor/Publicador/getInfoOfertaStringResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getInfoOfertaString/Fault/OfertaNoExisteException")
    })
    public String getInfoOfertaString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns servidor.DtOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/infoOfertaConfirmadaRequest", output = "http://Servidor/Publicador/infoOfertaConfirmadaResponse")
    public DtOfertaArray infoOfertaConfirmada();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getPaquetesCompradosRequest", output = "http://Servidor/Publicador/getPaquetesCompradosResponse")
    public DtPaqueteArray getPaquetesComprados(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtOfertaArray
     * @throws OfertaNoExisteException_Exception
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getOfertasSinPostularRequest", output = "http://Servidor/Publicador/getOfertasSinPostularResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/getOfertasSinPostular/Fault/UsuarioNoExisteException"),
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getOfertasSinPostular/Fault/OfertaNoExisteException")
    })
    public DtOfertaArray getOfertasSinPostular(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception, UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg10
     * @param arg11
     * @param arg12
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @param arg8
     * @param arg9
     * @throws OfertaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/altaOfertaRequest", output = "http://Servidor/Publicador/altaOfertaResponse", fault = {
        @FaultAction(className = OfertaRepetidaException_Exception.class, value = "http://Servidor/Publicador/altaOferta/Fault/OfertaRepetidaException")
    })
    public void altaOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        float arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7,
        @WebParam(name = "arg8", partName = "arg8")
        String arg8,
        @WebParam(name = "arg9", partName = "arg9")
        String arg9,
        @WebParam(name = "arg10", partName = "arg10")
        StringArray arg10,
        @WebParam(name = "arg11", partName = "arg11")
        String arg11,
        @WebParam(name = "arg12", partName = "arg12")
        String arg12)
        throws OfertaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getEmpresaOfertaRequest", output = "http://Servidor/Publicador/getEmpresaOfertaResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getEmpresaOferta/Fault/OfertaNoExisteException")
    })
    public String getEmpresaOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoPaqueteRequest", output = "http://Servidor/Publicador/getInfoPaqueteResponse")
    public String getInfoPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.Oferta
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getOfertaRequest", output = "http://Servidor/Publicador/getOfertaResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getOferta/Fault/OfertaNoExisteException")
    })
    public Oferta getOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/listarKeywordsRequest", output = "http://Servidor/Publicador/listarKeywordsResponse")
    public StringArray listarKeywords();

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws TOfertaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/agregarPaqueteRequest", output = "http://Servidor/Publicador/agregarPaqueteResponse", fault = {
        @FaultAction(className = TOfertaRepetidaException_Exception.class, value = "http://Servidor/Publicador/agregarPaquete/Fault/TOfertaRepetidaException")
    })
    public void agregarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5)
        throws TOfertaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @throws TOfertaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/agregarTOfertaRequest", output = "http://Servidor/Publicador/agregarTOfertaResponse", fault = {
        @FaultAction(className = TOfertaRepetidaException_Exception.class, value = "http://Servidor/Publicador/agregarTOferta/Fault/TOfertaRepetidaException")
    })
    public void agregarTOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2,
        @WebParam(name = "arg3", partName = "arg3")
        int arg3,
        @WebParam(name = "arg4", partName = "arg4")
        float arg4,
        @WebParam(name = "arg5", partName = "arg5")
        LocalDate arg5)
        throws TOfertaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns net.java.dev.jaxb.array.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getOfertaKeywordRequest", output = "http://Servidor/Publicador/getOfertaKeywordResponse")
    public StringArray getOfertaKeyword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws TOfertaRepetidaException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/agregarPTPRequest", output = "http://Servidor/Publicador/agregarPTPResponse", fault = {
        @FaultAction(className = TOfertaRepetidaException_Exception.class, value = "http://Servidor/Publicador/agregarPTP/Fault/TOfertaRepetidaException")
    })
    public void agregarPTP(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2)
        throws TOfertaRepetidaException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/modificarOfertaRequest", output = "http://Servidor/Publicador/modificarOfertaResponse")
    public void modificarOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws KeywordRepetida_Exception
     */
    @WebMethod(operationName = "AltaDeKeyword")
    @Action(input = "http://Servidor/Publicador/AltaDeKeywordRequest", output = "http://Servidor/Publicador/AltaDeKeywordResponse", fault = {
        @FaultAction(className = KeywordRepetida_Exception.class, value = "http://Servidor/Publicador/AltaDeKeyword/Fault/KeywordRepetida")
    })
    public void altaDeKeyword(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws KeywordRepetida_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.TOferta
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getTOfertaRequest", output = "http://Servidor/Publicador/getTOfertaResponse")
    public TOferta getTOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/inicioSesionRequest", output = "http://Servidor/Publicador/inicioSesionResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/Publicador/inicioSesion/Fault/Exception")
    })
    public boolean inicioSesion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns servidor.DtPaqueteArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/infoPaquetesRequest", output = "http://Servidor/Publicador/infoPaquetesResponse")
    public DtPaqueteArray infoPaquetes();

    /**
     * 
     * @return
     *     returns servidor.DtTipoOfertaArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/infoTOfertaRequest", output = "http://Servidor/Publicador/infoTOfertaResponse")
    public DtTipoOfertaArray infoTOferta();

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtOferta
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getDTOfertaRequest", output = "http://Servidor/Publicador/getDTOfertaResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getDTOferta/Fault/OfertaNoExisteException")
    })
    public DtOferta getDTOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPostulante
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoPostulanteRequest", output = "http://Servidor/Publicador/getInfoPostulanteResponse")
    public DtPostulante getInfoPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/incCantVisitasRequest", output = "http://Servidor/Publicador/incCantVisitasResponse")
    public void incCantVisitas(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPaquete
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getDTPaqueteRequest", output = "http://Servidor/Publicador/getDTPaqueteResponse")
    public DtPaquete getDTPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/finalizarOfertaRequest", output = "http://Servidor/Publicador/finalizarOfertaResponse")
    public void finalizarOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/checkVencimientoRequest", output = "http://Servidor/Publicador/checkVencimientoResponse")
    public boolean checkVencimiento(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/verificarOfertaRequest", output = "http://Servidor/Publicador/verificarOfertaResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/Publicador/verificarOferta/Fault/Exception")
    })
    public void verificarOferta(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        boolean arg1,
        @WebParam(name = "arg2", partName = "arg2")
        LocalDate arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoTipoRequest", output = "http://Servidor/Publicador/getInfoTipoResponse")
    public String getInfoTipo(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/compraPaqueteRequest", output = "http://Servidor/Publicador/compraPaqueteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Servidor/Publicador/compraPaquete/Fault/Exception")
    })
    public void compraPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPublicar
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoPublicarRequest", output = "http://Servidor/Publicador/getInfoPublicarResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/getInfoPublicar/Fault/OfertaNoExisteException")
    })
    public DtPublicar getInfoPublicar(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws OfertaNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtEmpresa
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoEmpresaRequest", output = "http://Servidor/Publicador/getInfoEmpresaResponse")
    public DtEmpresa getInfoEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns servidor.DtPostulacionArray
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getPostulacionesRequest", output = "http://Servidor/Publicador/getPostulacionesResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/getPostulaciones/Fault/UsuarioNoExisteException")
    })
    public DtPostulacionArray getPostulaciones(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/esEmpresaRequest", output = "http://Servidor/Publicador/esEmpresaResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/esEmpresa/Fault/UsuarioNoExisteException")
    })
    public boolean esEmpresa(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/estaPostuladoRequest", output = "http://Servidor/Publicador/estaPostuladoResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/estaPostulado/Fault/UsuarioNoExisteException")
    })
    public boolean estaPostulado(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/esPostulanteRequest", output = "http://Servidor/Publicador/esPostulanteResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/esPostulante/Fault/UsuarioNoExisteException")
    })
    public boolean esPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @return
     *     returns servidor.DtPostulacion
     * @throws UsuarioNoExisteException_Exception
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://Servidor/Publicador/getInfoPostulacionRequest", output = "http://Servidor/Publicador/getInfoPostulacionResponse", fault = {
        @FaultAction(className = UsuarioNoExisteException_Exception.class, value = "http://Servidor/Publicador/getInfoPostulacion/Fault/UsuarioNoExisteException")
    })
    public DtPostulacion getInfoPostulacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1)
        throws UsuarioNoExisteException_Exception
    ;

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @param arg3
     * @param arg4
     * @param arg5
     * @param arg6
     * @param arg7
     * @throws UsuarioRepetidoException_Exception
     */
    @WebMethod
    @Action(input = "http://Servidor/Publicador/crearPostulanteRequest", output = "http://Servidor/Publicador/crearPostulanteResponse", fault = {
        @FaultAction(className = UsuarioRepetidoException_Exception.class, value = "http://Servidor/Publicador/crearPostulante/Fault/UsuarioRepetidoException")
    })
    public void crearPostulante(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2,
        @WebParam(name = "arg3", partName = "arg3")
        String arg3,
        @WebParam(name = "arg4", partName = "arg4")
        String arg4,
        @WebParam(name = "arg5", partName = "arg5")
        String arg5,
        @WebParam(name = "arg6", partName = "arg6")
        String arg6,
        @WebParam(name = "arg7", partName = "arg7")
        String arg7)
        throws UsuarioRepetidoException_Exception
    ;

    /**
     * 
     * @throws OfertaNoExisteException_Exception
     */
    @WebMethod(operationName = "CargarDatos")
    @Action(input = "http://Servidor/Publicador/CargarDatosRequest", output = "http://Servidor/Publicador/CargarDatosResponse", fault = {
        @FaultAction(className = OfertaNoExisteException_Exception.class, value = "http://Servidor/Publicador/CargarDatos/Fault/OfertaNoExisteException")
    })
    public void cargarDatos()
        throws OfertaNoExisteException_Exception
    ;

}
