
package servidor;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "TOfertaRepetidaException", targetNamespace = "http://Servidor/")
public class TOfertaRepetidaException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private TOfertaRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public TOfertaRepetidaException_Exception(String message, TOfertaRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public TOfertaRepetidaException_Exception(String message, TOfertaRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: servidor.TOfertaRepetidaException
     */
    public TOfertaRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
